services:
  api:
    build:
      context: .
      dockerfile: src/TesteTwrt.WebApi/Dockerfile
    container_name: testeTwrt-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=testeTwrtDb;User=root;Password=root;
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: testeTwrt-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testeTwrtDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
